apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-hello-pipeline
spec:
  resources:
  - name: git-source-resource
    type: git
  - name: result-image
    type: image
  params:
  - default: none
    description: git push url
    name: gitPushUrl
    type: string
  workspaces:
  - name: output
  tasks:
    - name: generate-image-tag
      taskRef:
        name: generate-image-tag
      resources:
        inputs:
        - name: git-resource
          resource: git-source-resource
        outputs:
        - name: result-image
          resource: result-image
    - name: build-hello-python
      taskRef:
        name: build-hello-python
      params:
      - name: pathToDockerFile
        value: $(resources.inputs.git-resource.path)/source/Dockerfile
      - name: pathToContext
        value: $(resources.inputs.git-resource.path)/source
      - name: imageURL
        value: $(tasks.generate-image-tag.results.image-url)
      resources:
        inputs:
        - name: git-resource
          resource: git-source-resource
        outputs:
        - name: result-image
          resource: result-image
    - name: update-operations-git
      taskRef: 
        name: patch-deployment
      params:
        - name: imageURL
          value: $(tasks.generate-image-tag.results.image-url)
        - name: gitURL
          value: $(params.gitPushUrl)
        - name: sourceGitHash
          value: $(tasks.generate-image-tag.results.commit-tag)
      workspaces:
      - name: output
        workspace: output
      