apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-fe
  name: nginx-fe
  namespace: k8gb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-fe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-fe
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-fe
  name: nginx-fe
  namespace: k8gb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-fe
  type: ClusterIP

